version: '3.5'

services:
    backend:
        build: ./server
        networks:
            - 410final
        ports:
            - "3000:3000"
    
    frontend:
        build: ./app
        depends_on:
            - backend
        networks:
            - 410final
        ports:
            - "8080:8080"
            
networks:
    410final:
        driver: bridge
